name: "Auto Merge"
description: "Enables auto-merge."
author: "Ken Howard <ken@kenhoward.dev>"
inputs:
  enable:
    required: false
    default: true
  token:
    required: true
    description: "a token with 'repo' privilege"
runs:
  using: 'node12'
  main: 'dist/index.js'
